"""baseline_full_schema

Revision ID: 13d929a8d02d
Revises: 
Create Date: 2026-07-01 22:25:55.894166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13d929a8d02d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_daily_tests_roadmap_id'), 'daily_tests', ['roadmap_id'], unique=False)
    op.drop_constraint('daily_tests_roadmap_id_fkey', 'daily_tests', type_='foreignkey')
    op.create_foreign_key(None, 'daily_tests', 'roadmaps', ['roadmap_id'], ['id'])
    op.alter_column('password_reset_otps', 'is_used',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('password_reset_otps', 'attempts_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_reset_otps_user_active', table_name='password_reset_otps', postgresql_where='(is_used = false)')
    op.create_index(op.f('ix_password_reset_otps_user_id'), 'password_reset_otps', ['user_id'], unique=False)
    op.add_column('roadmaps', sa.Column('generation_status', sa.String(), nullable=True))
    op.add_column('roadmaps', sa.Column('generation_error', sa.Text(), nullable=True))
    op.add_column('roadmaps', sa.Column('days_status', sa.JSON(), nullable=True))
    op.alter_column('roadmaps', 'is_confirmed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('roadmaps', 'outline',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('roadmaps', 'detailed_days',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_profiles', 'known_tools',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_profiles', 'target_skills',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_profiles', 'interests',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_profiles', 'certifications_done',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_profiles', 'certifications_target',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_profiles', 'extra_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint('user_profiles_user_id_key', 'user_profiles', type_='unique')
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.drop_constraint('user_profiles_user_id_fkey', 'user_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'user_profiles', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'profession',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profession',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'Other'::character varying"),
               existing_nullable=False)
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.create_foreign_key('user_profiles_user_id_fkey', 'user_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.create_unique_constraint('user_profiles_user_id_key', 'user_profiles', ['user_id'])
    op.alter_column('user_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('user_profiles', 'extra_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               existing_nullable=True)
    op.alter_column('user_profiles', 'certifications_target',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               existing_nullable=True)
    op.alter_column('user_profiles', 'certifications_done',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               existing_nullable=True)
    op.alter_column('user_profiles', 'interests',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               existing_nullable=True)
    op.alter_column('user_profiles', 'target_skills',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               existing_nullable=True)
    op.alter_column('user_profiles', 'known_tools',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               existing_nullable=True)
    op.alter_column('roadmaps', 'detailed_days',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               existing_nullable=True)
    op.alter_column('roadmaps', 'outline',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               existing_nullable=True)
    op.alter_column('roadmaps', 'is_confirmed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.drop_column('roadmaps', 'days_status')
    op.drop_column('roadmaps', 'generation_error')
    op.drop_column('roadmaps', 'generation_status')
    op.drop_index(op.f('ix_password_reset_otps_user_id'), table_name='password_reset_otps')
    op.create_index('idx_reset_otps_user_active', 'password_reset_otps', ['user_id'], unique=False, postgresql_where='(is_used = false)')
    op.alter_column('password_reset_otps', 'attempts_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('password_reset_otps', 'is_used',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_constraint(None, 'daily_tests', type_='foreignkey')
    op.create_foreign_key('daily_tests_roadmap_id_fkey', 'daily_tests', 'roadmaps', ['roadmap_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_daily_tests_roadmap_id'), table_name='daily_tests')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
